# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Dockerfile"
# Hadolint is going to hurt your feelings!

on:  # yamllint disable-line rule:truthy
    pull_request:
        paths:
        - "**/Dockerfile"
        - ".hadolint.yaml"
    push:
        branches:
        - "master"
        paths:
        - "**/Dockerfile"
        - ".hadolint.yaml"
    workflow_call: null

permissions: {}  # yamllint disable-line rule:braces
#permissions: "read-all"
#permissions:
#    contents: "read" # Private repositories need read permission

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    hadolint:
        name: "🐳 Hadolint"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4.1.5"
        -
            name: "Check Dockerfiles"
            uses: "hadolint/hadolint-action@v3.3.0"
