# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrity"
# This workflow prevents earthquakes.

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces
#permissions: "read-all"
#permissions:
#    contents: "read" # Private repositories need read permission

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    call_workflow_integrity:
        name: "Integrity"
        uses: "./.github/workflows/reusable-integrity.yml"
        with:
            executables: >-
                bin/make-reusable-integrity.sh
            not-printable-ascii-paths: >-
                bin/
                src/
                resources/
                tests/
            export-excludes: >-
                --exclude="*/*"
            exported-paths: >-
                LICENSE
                README.md
                bin/
                composer.json
                package.json
                resources/
                src/
