# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Integrity"
# This action prevents earthquakes.

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"

permissions: {}  # yamllint disable-line rule:braces
#permissions: "read-all"
#permissions:
#    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    call_workflow_integrity:
        name: "Integrity"
        uses: "./.github/workflows/reusable-integrity.yml"
        with:
            not-printable-ascii-paths: >-
                src/
                resources/
                tests/
            export-excludes: >-
                --exclude="src" --exclude="src/*"
                --exclude="resources" --exclude="resources/*"
            exported-paths: >-
                LICENSE
                README.md
                composer.json
                package.json
