on:
    pull_request: null

jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
        -
            uses: actions/checkout@v3
            with:
                # To check out the actual pull request commit, not the merge commit
                ref: ${{ github.event.pull_request.head.sha }}
                fetch-depth: 0
        -
            uses: JetBrains/qodana-action@v2023.2
            env:
                QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
